name: PlatformIO CI

# GitHub Actions 的工作流语法 : https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  push:
    paths: # 推送以下文件时，就会运行工作流
      - "examples/**"
      - ".github/workflows/platformio.yml"
      - "platformio.ini"

jobs:
  build:
    runs-on: ubuntu-latest  # 指定的运行器环境中运行 [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        example: 
            - examples/bq25896/main
            - examples/bq27220/main
            - examples/display_test/main
            - examples/factory/main
            - examples/GPS/main
            - examples/io_extend/main
            - examples/lora_recv/main
            - examples/lora_send/main
            - examples/lvgl_test/main
            - examples/rtc_pcf8563/main
            - examples/sd_card/main
            - examples/touch/main

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO
        run: |
          export PLATFORMIO_SRC_DIR=${{ matrix.example }}
          pio run
